config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
    resources :orders
  end
  devise_for :users
  get 'home/index'
  get 'signedinuserprofile' => 'profiles#signedinuserprofile'
  root :to => 'home#index'

  resources :bikes

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :profile
  has_many :rent_items
end

app/controllers/orders_controller.rb
require 'my_logger'
require 'calculator'
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    #get the profile with id 
    @profile = Profile.find(params[:profile_id])
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @orders = Order.all
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
    @profile = Profile.find(params[:profile_id])
  end

  # GET /orders/1/edit
  def edit
    @orders = Order.all
    @profile = Profile.find(params[:profile_id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @user = User.find(params[:profile_id])
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.build
    params[:bike_ids].each do |bike_id|  
    #@order.days = @order.rent_items.days
    @order.rent_items.build(bike_id: bike_id)
    end
    @order.save!

    #retreive the object MyLogger class
    logger = MyLogger.instance
    logger.logInformation("A new order has been created for profile: " + @order.profile.user_id.to_s + " Order number: " + @order.id.to_s)  
    if @order.save
     #use the UserMailer to send a mail to the currently signed in user to tell them they have completed the order successfuly
     UserMailer.order_email(@user).deliver_now
      redirect_to profile_order_url(@profile, @order)
    else 
      render :action => "new"
    end
  end

  #method to calculate total price
  def sum
      @num1 = params[:bike.days]
      @num2 = params[:bike.price]
      @result = Calculator.total(@num1.to_i, @num2.to_i)
  end

   # respond_to do |format|
    #  if @order.save
     #   format.html { redirect_to @order, notice: 'Order was successfully created.' }
      #  format.json { render :show, status: :created, location: @order }
      #else
       # format.html { render :new }
       # format.json { render json: @order.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @profile_order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

   

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:bike, :price, :days, :total, :bike_id, :profile_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for @order, :url => profile_orders_path do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bike %><br>
    <%= f.text_field :bike %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :days %><br>
    <%= f.number_field :days %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total %>
  </div>
  <div class="field">
    <%= f.label :bike_id %><br>
    <%= f.number_field :bike_id %>
  </div>
  <div class="field">
    <%= f.label :profile_id %><br>
    <%= f.text_field :profile_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Bike</th>
      <th>Price</th>
      <th>Days</th>
      <th>Total</th>
      <th>Order Number</th>
      <th>Profile</th>
    <%#  <th>Bike</th>
      <th>Profile</th> %>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.bike %></td>
        <td><%= order.price %></td>
        <td><%= order.days %></td>
        <td><%= order.total %></td>
        <td><%= order.id %></td>
        <td><%= order.profile_id %></td>
      <%#  <td><%= order.bike_id %>
      <%# <td><%= order.profile_id %>
       <%# <td><%= link_to 'Show', profile_order(@profile) %>
       <%#<td><%= link_to 'Edit', edit_profile_order_path(@profile, @order) %>
       <% if current_user.admin? %>
       <td><%= link_to 'Destroy', profile_orders_path(@order.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
       <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Order', new_profile_order_path %>
<%# <%= link_to 'Edit', edit_profile_order_path(@id) %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Your Order Summary</h2>
<% @order.rent_items.each do |rent_item| %>
<p>
  <strong>Bike Description:</strong>
  <%= rent_item.bike.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= rent_item.bike.price %>
</p>

<p>
  <strong>Days:</strong>
  <%= rent_item.days %>
</p>
<% end %>
<p>
<p>
  <strong>Total: <%= @order.total %></strong>
</p>
  <strong>Thanks for your order <%= @order.profile.firstname %> </strong>
</p>
<p>
  <strong>This Order reference: <%= @order.id %></strong>
</p>
<p>
  <strong>This Order created at: <%= @order.created_at %></strong>
</p>

<%# link_to 'Edit', edit_profile_order_path(@profile, @order) %> |
<%= link_to 'Back', profile_orders_path(@profile) %> 