config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
    resources :orders
  end
  devise_for :users
  get 'home/index'
  get 'signedinuserprofile' => 'profiles#signedinuserprofile'
  root :to => 'home#index'

  resources :bikes

end

app/models/bike.rb
class Bike < ActiveRecord::Base
	has_many :rent_items

	def self.search(search_for)
		Bike.where("description = ?", search_for)
	end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin, :only => [:edit, :destroy]
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all

    if params[:search]
      # select all the bikes that match the search
      @bikes = Bike.search(params[:search])
      #order the selected rows in assending order by created at
      @bikes = @bikes.order("created_at ASC")
    else
      #order all reows in decending order by created_at field
      @bikes = @bikes.order("created_at DESC")
    end
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
    @bikes = Bike.all
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:description, :price, :days, :image_url)
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :days %><br>
    <%= f.number_field :days %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Bikes available to rent</h1>

<h2>Search for a bike</h2>
<%= form_tag(bikes_path, :method => "get") do %>
  <%= text_field_tag :search, params[:search], :placeholder => "Search for a bike" %>
  <%= submit_tag "Search" %>
<% end %>

<p></p>

<%# form to collect user input for the order %>
<h3> Create an order </h3>
<%= form_for [Profile.find_by_user_id(current_user.id), Order.new] do |f| %>
<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th>Number of Days</th>
      <th></th>
      <th>Add to order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.description %></td>
        <%# number to currency helper to show euro symbol %>
        <td><%= number_to_currency(bike.price, unit: "€") %></td>
        <%# text input to say how many days to rent bike %>
        <td><%= text_field_tag "days[]", bike.days %></td>
        <%# image tag to show image from url %>
        <td><%= image_tag(bike.image_url, :class => 'list_image') %></td>
        <%# checkbox to add bikes to order, passing bike id's %>
        <td><%= check_box_tag "bike_ids[]",bike.id %></td>
        <%# only allow admin to edit bikes %>
        <% if current_user.admin? %>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike)%></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%# submitting form will create a POST  %>
<%= f.submit 'Submit Order' , class: 'btn' %>
<% end %>

<br>

<%# Only allow an admin to create a new bike %>

<% if current_user.admin? %>
<%= link_to 'New Bike', new_bike_path %>
<% end %>

app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @bike.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @bike.price %>
</p>

<p>
  <strong>Days:</strong>
  <%= @bike.days %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @bike.image_url %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>