config/routes.rb
Rails.application.routes.draw do
  
  resources :profiles do
    resources :orders
  end
  devise_for :users
  get 'home/index'
  get 'signedinuserprofile' => 'profiles#signedinuserprofile'
  root :to => 'home#index'

  resources :bikes

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bikerental</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-inverse">
		<div class="navbar-inner">
			<div class="container"> 
			<%= link_to "Donals Bike Rental Site", home_index_path, id: "logo" %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", home_index_path %></li>
					<li><%= link_to "Bikes", bikes_path %></li>
					<%# check if user is signed in and has a profile before showing orders%>
					<% if user_signed_in? && current_user.profile.present? %>
					<li><%= link_to "My Orders", profile_orders_path(Profile.find_by_user_id(current_user.id)) %></li>
					<% end %>
					<% if user_signed_in? %>
					<li><%= link_to 'Logout' , destroy_user_session_path, :method => :delete%></li>
					<% else %>
					<li><%= link_to 'Sign in' , new_user_session_path %></li>
					<li><%= link_to 'Register' , new_user_registration_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</header>


<div class="container">
<%= yield %>


</div>
<p class="notice"><%= notice %></p>
<p class="alert"><% alert %></p>
</body>
</html>

app/views/layouts/order_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for placing an order</h1>
    <p>
      You have successfully placed an order with Donals bikes
    </p>
    <p>Thanks for Ordering!</p>
  </body>
</html>

app/views/layouts/order_email.text.erb
Thank you for ordering a bike form Donals bike rental!

app/views/layouts/welcome_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Thanks for creating an account with donals bikes</h1>
    <p>
      You have successfully created an account
    </p>
    <p>Thanks for joining!</p>
  </body>
</html>

app/views/layouts/welcome_email.text.erb
Thank you for creating an account on donals bikes